### PR TITLE
adding typings in package.json

### PR DESCRIPTION
**Pull request by ridomin**
The react demo did not work with the default instructions because typings were not found.
To solve it, I've added typings to the devDependencies, and invoke it in the postintall event from package.json

### CODE REVIEW

**Comment by bowdenk7** [comment]
Good catch. We want it to work out of the box though. Users won't be running npm install. If you don't mind, remove `typings` from `package.json` and `.gitignore` and commit the entire "typings folder". 

Or just remove that commit from your PR and I can fix it.

**Comment by awclives** [comment]
Anything happen here?  I tried to get the react-reddit demo running, only to find that it is broken due to missing typings.

**Comment by bowdenk7** [comment]
@awclives Thanks for the bump. Fixed this issue with #3

**Comment by bowdenk7** [comment]
Closing this PR as it has been moved [here](https://github.com/Microsoft/TypeScriptSamples/pull/100)

**Pull request closed without merging**
